### ISSUE TITLE
Installed plugins lists incorrect graylog-plugin-beats version

### ISSUE THREAD

**Issue by imperatives** [Graylog2/graylog-plugin-beats#11]
After replacing 1.0.1 jar with 1.0.3 and restarting graylog the displayed graylog-plugin-beats plugin version is still listed as 1.0.1.

**Comment by joschi** [comment]
@imperatives Yes, that's a known issue: https://github.com/Graylog2/graylog-plugin-beats/blob/1.0.3/src/main/java/org/graylog/plugins/beats/BeatsInputPluginMetaData.java#L50

This being said, the latest version of the Beats plugin is being shipped with Graylog 2.1.0 and higher.
