### ISSUE TITLE
Internal fields are prefixed with beats name

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/graylog-plugin-beats#18]
Special fields like ` gl2_source_collector` should not be prefixed with the Beats name in order to keep functionality of the fields. This can be done for all `gl2_` fields.

Winlogbeat snippet for reproduction:

```
fields:
  gl2_source_collector: foo
fields_under_root: true
```
this leads to a field called `winlogbeat_gl2_source_collector`.

**Comment by joschi** [comment]
@mariussturm The latest version of the Beats plugin will properly handle the `fields` field in the payload of all types of Beats (was only handled for Filebeat before).

This being said, `fields_under_root` should be set to `false` (default) for this to work.

**Comment by mariussturm** [comment]
Alright, thanks!
