### ISSUE TITLE
Support "docker" and "kubernetes" metadata field with new libbeat version

### ISSUE THREAD

**Issue by tanapoln** [Graylog2/graylog-plugin-beats#25]
Currently, libbeat support adding docker metadata and kubernetes metadata as you can see from this document: https://github.com/elastic/beats/blob/master/libbeat/docs/processors-using.asciidoc#adding-docker-metadata

Right now, graylog beats plugins discard other all well-known root fields which will remove all of above metadata.

I didn't see any configuration on beats plugins to allow accepting additional field.

If there is no configuration available, we should support it.
I propose 2 ways to do this (I can help contribute):
1) the plugins didn't support dynamic fields configuration, the plugins will add all datas from "docker" or "kubernetes" directly to the message (I think this is the easiest way)

2) support dynamic fields configuration on UI, and maybe, with some mechanism to flatten nested values to the root (not sure if we should do this).

**Comment by ishworgurung** [comment]
hey fellas,

any update on this? ta

**Comment by ATLJLawrie** [comment]
@tanapoln the creator of the issue has a branch in his fork that has done a good portion of the work.  
https://github.com/tanapoln/graylog-plugin-beats/commit/6c7a9325c7666dd3b87cdbdef39649137828148b I've been trying to add the few extra fields and get a JAR out of that guy
