### ISSUE TITLE
Complete documentation with a full configuration example

### ISSUE THREAD

**Issue by fadjer** [Graylog2/graylog-plugin-beats#31]
Hi,

Could you please supply a full configuration example? Especially how Logstash needs to send data to Graylog... We are not necessarily ELK experts :-( 

Many thanks

**Comment by joschi** [comment]
@fadjer Logstash doesn't have a Beats output. One way to use Logstash to send log messages to Graylog would be to use the [GELF output](https://www.elastic.co/guide/en/logstash/6.1/plugins-outputs-gelf.html) (and a GELF input on Graylog's side).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by fadjer** [comment]
Sorry, I'm a bit confused. Your plugin is used to receive data from logstash-forwards and the Beats family? right ? 
How to configure logstash to send data to the input we made using your plugin? is it possible to send data directely from a packetbeat for example to gralog2 using your input?

Many thanks

**Comment by joschi** [comment]
> How to configure logstash to send data to the input we made using your plugin?

Logstash doesn't have a beats (or lumberjack) output.

> is it possible to send data directely from a packetbeat for example to gralog2 using your input?

Yes

Please move this discussion to the aforementioned discussion forum.

**Comment by fadjer** [comment]
Sorry. There's indeed a full example here:
https://www.graylog.org/blog/72-tapping-wires-for-lean-security-monitoring-dns-request-analysis-with-open-source-software
