### ISSUE TITLE
Filebeat cannot get message from Windows Apache Logs

### ISSUE THREAD

**Issue by vandat07** [Graylog2/graylog-plugin-beats#34]
Hello,

I have configured filebeat on windows to monitor php Apache logs by following this document: http://docs.graylog.org/en/3.1/pages/sidecar.html#first-start

Here is filebeat configuration:

> fields_under_root: true
> fields.collector_node_id: ${sidecar.nodeName}
> fields.gl2_source_collector: ${sidecar.nodeId}
> 
> output.logstash:
>    hosts: ["My_GrayLogServer_IP:5044"]
> 
> path:
>   data: C:\Program Files\Graylog\sidecar\cache\filebeat\data
>   logs: C:\Program Files\Graylog\sidecar\logs
> tags:
>   - windows
> filebeat.config.inputs:
>   type: log
>   enabled: true
>   paths:
>     - C:\Wamp\apache2\logs\*

The collector is now in RUNNING state but still cannot get messages. Below is filebeat log:

> 2020-01-03T15:25:37.002+0700	INFO	instance/beat.go:544	Home path: [C:\Program Files\Graylog\sidecar] Config path: [C:\Program Files\Graylog\sidecar] Data path: [C:\Program Files\Graylog\sidecar\cache\filebeat\data] Logs path: [C:\Program Files\Graylog\sidecar\logs]
> 2020-01-03T15:25:37.004+0700	INFO	instance/beat.go:551	Beat UUID: 50824907-0a65-4a49-8176-a102b5159eb1
> 2020-01-03T15:25:37.004+0700	INFO	[beat]	instance/beat.go:768	Beat info	{"system_info": {"beat": {"path": {"config": "C:\\Program Files\\Graylog\\sidecar", "data": "C:\\Program Files\\Graylog\\sidecar\\cache\\filebeat\\data", "home": "C:\\Program Files\\Graylog\\sidecar", "logs": "C:\\Program Files\\Graylog\\sidecar\\logs"}, "type": "filebeat", "uuid": "50824907-0a65-4a49-8176-a102b5159eb1"}}}
> 2020-01-03T15:25:37.005+0700	INFO	[beat]	instance/beat.go:777	Build info	{"system_info": {"build": {"commit": "e193f6d68b25b7ddbe3a3ed8d60bc07fea1ef800", "libbeat": "6.4.2", "time": "2018-09-26T12:41:59.000Z", "version": "6.4.2"}}}
> 2020-01-03T15:25:37.005+0700	INFO	[beat]	instance/beat.go:780	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":3,"version":"go1.10.3"}}}
> 2020-01-03T15:25:37.009+0700	INFO	[beat]	instance/beat.go:784	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2019-12-31T15:38:56.47+07:00","hostname":"WEBAPP03","ips":["fe80::61ca:a665:166c:f850/64","MyClientIP/24","MyClientIP2/24","::1/128","127.0.0.1/8","fe80::5efe:a2e:1fc9/128","fe80::5efe:a2e:1fca/128","2001:0:2851:782c:307d:ac4:2103:576/64","fe80::307d:ac4:2103:576/64"],"kernel_version":"10.0.14393.2248 (rs1_release.180427-1804)","mac_addresses":["00:15:5d:64:17:01","00:00:00:00:00:00:00:e0","00:00:00:00:00:00:00:e0"],"os":{"family":"windows","platform":"windows","name":"Windows Server 2016 Standard","version":"10.0","major":10,"minor":0,"patch":0,"build":"14393.2248"},"timezone":"+07","timezone_offset_sec":25200,"id":"a0a101f7-9dd2-4ca6-98d1-ff4eee40ae53"}}}
> 2020-01-03T15:25:37.009+0700	INFO	instance/beat.go:273	Setup Beat: filebeat; Version: 6.4.2
> 2020-01-03T15:25:37.010+0700	INFO	pipeline/module.go:98	Beat name: WEBAPP03
> 2020-01-03T15:25:37.010+0700	INFO	instance/beat.go:367	filebeat start running.
> 2020-01-03T15:25:37.010+0700	INFO	[monitoring]	log/log.go:114	Starting metrics logging every 30s
> 2020-01-03T15:25:37.010+0700	INFO	registrar/registrar.go:134	Loading registrar data from C:\Program Files\Graylog\sidecar\cache\filebeat\data\registry
> 2020-01-03T15:25:37.010+0700	INFO	registrar/registrar.go:141	States Loaded from registrar: 0
> 2020-01-03T15:25:37.010+0700	WARN	beater/filebeat.go:371	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
> 2020-01-03T15:25:37.010+0700	INFO	crawler/crawler.go:72	Loading Inputs: 0
> 2020-01-03T15:25:37.010+0700	INFO	crawler/crawler.go:106	Loading and starting Inputs completed. Enabled inputs: 0
> 2020-01-03T15:25:37.010+0700	INFO	cfgfile/reload.go:141	Config reloader started
> 2020-01-03T15:25:37.011+0700	INFO	cfgfile/reload.go:196	Loading of config files completed.
> 2020-01-03T15:26:07.094+0700	INFO	[monitoring]	log/log.go:141	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":109,"time":{"ms":109}},"total":{"ticks":109,"time":{"ms":109},"value":109},"user":{"ticks":0}},"info":{"ephemeral_id":"7b26b161-b4d8-43e2-8e4d-5da2e2f00355","uptime":{"ms":30037}},"memstats":{"gc_next":4194304,"memory_alloc":2044032,"memory_total":3635056,"rss":18432000}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0},"reloads":1},"output":{"type":"logstash"},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}},"system":{"cpu":{"cores":3}}}}}
> 2020-01-03T15:26:37.011+0700	INFO	[monitoring]	log/log.go:141	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":109},"total":{"ticks":109,"value":109},"user":{"ticks":0}},"info":{"ephemeral_id":"7b26b161-b4d8-43e2-8e4d-5da2e2f00355","uptime":{"ms":60037}},"memstats":{"gc_next":4194304,"memory_alloc":2092400,"memory_total":3683424,"rss":1871872}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}}}}}
> 2020-01-03T15:27:07.011+0700	INFO	[monitoring]	log/log.go:141	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":109},"total":{"ticks":109,"value":109},"user":{"ticks":0}},"info":{"ephemeral_id":"7b26b161-b4d8-43e2-8e4d-5da2e2f00355","uptime":{"ms":90038}},"memstats":{"gc_next":4194304,"memory_alloc":2124960,"memory_total":3715984,"rss":-73728}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}}}}}
> 2020-01-03T15:27:37.013+0700	INFO	[monitoring]	log/log.go:141	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":109},"total":{"ticks":140,"time":{"ms":31},"value":140},"user":{"ticks":31,"time":{"ms":31}}},"info":{"ephemeral_id":"7b26b161-b4d8-43e2-8e4d-5da2e2f00355","uptime":{"ms":120037}},"memstats":{"gc_next":4194304,"memory_alloc":2160256,"memory_total":3751280,"rss":266240}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}}}}}

I spent 3 days to fix this issue but no solution. Coul you please tell me what have done wrong?

Thanks a lot,
Van Dat

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
