### ISSUE TITLE
Await inside BeatsFrameDecoder

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-beats#6]
I found this line in [BeatsFrameDecoder](https://github.com/Graylog2/graylog-plugin-beats/blob/master/src/main/java/org/graylog/plugins/beats/BeatsFrameDecoder.java).sendACK:
`channel.write(buffer).awaitUninterruptibly();`
Why should we block I/O thread to wait write operation?
Is it possible to receive duplicate message, if won't wait?
Or Netty is smart enough to not block in such case?

**Comment by joschi** [comment]
@hc4 Good catch, thanks!
