### ISSUE TITLE
Beats plugin version still 1.0.1

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-beats#7]
Plugin version in [BeatsInputPluginMetaData.java](https://github.com/Graylog2/graylog-plugin-beats/blob/master/src/main/java/org/graylog/plugins/beats/BeatsInputPluginMetaData.java#L50) not updated in new releases
So in UI there is still displayed v1.0.1

**Comment by joschi** [comment]
Fixed in f1f5a41681e31139a318f95455980c92fbaac37a.
