### ISSUE TITLE
incorrectly typed topbeat percent fields

### ISSUE THREAD

**Issue by Lollaskates** [Graylog2/graylog-plugin-beats#9]
when using the plugin, trying to build queries / graphs on a few _p fields wasn't working as expected.

Upon looking at my index, these fields had the type "long":
          "topbeat_swap_used_p" : {
            "type" : "long"
          },
          "topbeat_fs_used_p" : {
            "type" : "long"
          }, 

These fields contain percent data, in the decimal form 0.86 (or 86%) and the other _p percent fields are correctly typed double. Is topbeat itself emitting the messages with the wrong type, or is this plugin incorrectly ingesting them? In the meantime I can do an extractor to convert it I suppose.

**Comment by joschi** [comment]
@Lollaskates This sounds like a case of dynamic mapping gone wrong.

You might want to create a [custom index mapping](http://docs.graylog.org/en/2.0/pages/configuration/elasticsearch.html#custom-index-mappings) in which you set those fields to the correct type.

The plugin itself is writing the values correctly.
